"""Storage helpers for git-cognition."""

from .git_notes import (
    CONFIG_ENABLED_KEY,
    CONFIG_SCHEMA_KEY,
    InvalidSessionBlobError,
    MissingSessionBlobError,
    MissingSessionNoteError,
    attach_session_to_commit,
    commits_between,
    current_head,
    get_changed_files,
    get_commit_date,
    get_commit_message,
    get_line_blame,
    get_line_blame_text,
    get_tracked_line_context,
    init_tracking,
    is_tracking_enabled,
    iter_sessions,
    read_session,
    read_session_for_commit,
    resolve_commit,
    resolve_session_id,
    write_session,
)

from .schema import SCHEMA_VERSION, Session

__all__ = [
    "CONFIG_ENABLED_KEY",
    "CONFIG_SCHEMA_KEY",
    "InvalidSessionBlobError",
    "MissingSessionBlobError",
    "MissingSessionNoteError",
    "SCHEMA_VERSION",
    "Session",
    "attach_session_to_commit",
    "commits_between",
    "current_head",
    "get_changed_files",
    "get_commit_date",
    "get_commit_message",
    "get_line_blame",
    "get_line_blame_text",
    "get_tracked_line_context",
    "init_tracking",
    "is_tracking_enabled",
    "iter_sessions",
    "read_session",
    "read_session_for_commit",
    "resolve_commit",
    "resolve_session_id",
    "write_session",
]
